/datum/skills/civilian/nerva/captain
	name = "CSCSS Nerva Captain"
	skills = list(
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_POLICE = SKILL_POLICE_MAX,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
	)


/datum/skills/civilian/nerva/cmo
	name = "CSCSS Nerva Chief Medical Officer"
	skills = list (
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MASTER,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
	)


/datum/skills/civilian/nerva/hos
	name = "CSCSS Nerva Head of Security"
	skills = list (
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_POLICE = SKILL_POLICE_MAX,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
	)


/datum/skills/civilian/nerva/ce
	name = "CSCSS Nerva Chief Engineer"
	skills = list (
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
	)


/datum/skills/civilian/nerva/security
	name = "CSCSS Nerva Security Officer"
	skills = list (
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
	)


/datum/skills/civilian/nerva/doctor
	name = "CSCSS Nerva Medical Specialist"
	skills = list (
		SKILL_ENDURANCE = SKILL_ENDURANCE_WEAK,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
	)


/datum/skills/civilian/nerva/engineer
	name = "CSCSS Nerva Ship Technician"
	skills = list (
		SKILL_ENDURANCE = SKILL_ENDURANCE_WEAK,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
	)
